name: Javadoc Generation
on:
  push:
    branches:
      - "master"
      - "testing-*"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    
      # Set up our environment
  
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up the JDK environment
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: "temurin"
          cache: gradle
      
      # # Install our dependencies by building the app, discarding the build, extracting and uploading external Javadocs. The external Javadocs can then be linked and the dependencies given to the CLASSPATH to be used
      
      - name: Import dependencies with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew --version
          ./gradlew build
          rm -rf ./docs
          ./gradlew extractJavadoc
          ls ./docs/7.0.0/

      # Locate our dependencies, build a classpath using them, append Android itself to said classpath, and run the Javadoc command with our flags. All of this, especially the dependendy preperation, is critical to the Javadoc command succeeding. It will fail due to a JDK bug affecting all versions <18, which sadly includes us due to FTC's reliance on Gradle 7. Talk to @tom-ricci amd @MatthewL246 before editing anything to do with this step

      - name: Generate documentation with Javadoc
        run: |
          echo '-classpath "./FtcRobotController/:' >> ./jdtclsp.txt
          aarray=( $(find ~/.gradle/caches/transform*/ -name "classes.jar"  -not -type d) )
          jarray=( $(find ~/.gradle/caches/module*/ -name "*.jar"  -not -type d) )
          rarray=( $(find ~/.gradle/caches/ -name "res" -type d) )
          marray=( $(find ~/.gradle/caches/ -name "AndroidManifest.xml"  -not -type d) )
          for i in ${aarray[@]}
          do
              echo $i >> ./jdtclsp.txt
              echo ":" >> ./jdtclsp.txt
          done
          for i in ${jarray[@]}
          do
              echo $i >> ./jdtclsp.txt
              echo ":" >> ./jdtclsp.txt
          done
          for i in ${rarray[@]}
          do
              echo $i >> ./jdtclsp.txt
              echo ":" >> ./jdtclsp.txt
          done
          for i in ${marray[@]}
          do
              echo $i >> ./jdtclsp.txt
              echo ":" >> ./jdtclsp.txt
          done
          echo '/usr/local/lib/android/sdk/platforms/android-29/android.jar"' >> ./jdtclsp.txt
          STR=$( cat ./jdtclsp.txt )
          STR=${STR//$'\n'/}
          rm -rf ./jdtclsp.txt
          echo $STR >> ./jdtclsp.txt
          rm -rf ./javadoc-output/
          mkdir ./javadoc-output/
          javadoc -Xdoclint:none -public -splitindex -use -author -version -d ./javadoc-output -link https://docs.oracle.com/en/java/javase/11/docs/api/ -link https://xaverianteamrobotics.github.io/FtcRobotController/javadocs/libs/ftccommon/ -link https://xaverianteamrobotics.github.io/FtcRobotController/javadocs/libs/hardware/ -link https://xaverianteamrobotics.github.io/FtcRobotController/javadocs/libs/inspection/ -link https://xaverianteamrobotics.github.io/FtcRobotController/javadocs/libs/onbotjava/ -link https://xaverianteamrobotics.github.io/FtcRobotController/javadocs/libs/robotcore/ @./jdtclsp.txt $(find ./TeamCode/ -name "*.java" -not -type d) --ignore-source-errors
          echo -e "\n\n\n\n------------------------------\nDEBUG LOGS START\n------------------------------\n\n\n\n"
          echo -e "CLASSPATH:\n\n"
          cat ./jdtclsp.txt
          echo -e "\n\n\nINPUT:\n\n"
          find ./TeamCode/ -name "*.java" -not -type d
          echo -e "\n\n\nOUTPUT:\n\n"
          ls ./javadoc-output/
          echo -e "\n\n\n\n------------------------------\nDEBUG LOGS END\n------------------------------\n\n\n\n"

      # Upload an Artifact of the Javadoc if for whatever reason one might need to download one

      - name: Upload generated Javadoc to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Javadoc-output
          path: ./javadoc-output/
          
      # Upload build reports and the Javadoc to Pages to access online

      - name: Upload generated Javadoc to Pages
        run: |
          # Set up Git and environment variables
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          shopt -s dotglob
          export BRANCH_NAME=$(echo $GITHUB_REF | sed -e "s/refs\/heads\///")
          # Move Javadoc output and build reports
          mv javadoc-output/ ..
          mkdir ../team-reports/
          mv ./TeamCode/build/reports/*  ../team-reports/
          mkdir ../sdk-reports/
          mv ./FtcRobotController/build/reports/* ../sdk-reports/
          # Checkout gh-pages branch
          git reset --hard HEAD
          git clean -f -d -x
          git remote set-branches origin --add 'gh-pages'
          git fetch -a -v
          git checkout gh-pages
          # Copy Javadoc docs to gh-pages
          rm -rf ./javadocs/${BRANCH_NAME}/ || true
          mkdir -p ./javadocs/${BRANCH_NAME}/
          mv ../javadoc-output/* ./javadocs/${BRANCH_NAME}/
          # Copy build reports to gh-pages
          rm -rf ./reports/${BRANCH_NAME}/ || true
          mkdir -p ./reports/${BRANCH_NAME}/team-reports/
          mkdir -p ./reports/${BRANCH_NAME}/sdk-reports/
          mv ../team-reports/* ./reports/${BRANCH_NAME}/team-reports/
          mv ../sdk-reports/* ./reports/${BRANCH_NAME}/sdk-reports/
          mv ./reports/${BRANCH_NAME}/team-reports/lint-results-debug.html ./reports/${BRANCH_NAME}/team-reports/index.html || true
          mv ./reports/${BRANCH_NAME}/sdk-reports/lint-results-debug.html ./reports/${BRANCH_NAME}/sdk-reports/index.html || true
          # Commit and push changes
          git add -A
          git commit -a -m "Javadoc documentation update ($GITHUB_RUN_NUMBER)
          Information:
            Repository: $GITHUB_REPOSITORY
            Branch: $GITHUB_REF
            Commit: $GITHUB_SHA
            Who triggered action: $GITHUB_ACTOR"
          git push
