name: Javadoc Generation
on:
  push:
    branches:
      - "master"
      - "testing-*"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up the JDK environment
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: "temurin"
          cache: gradle
      
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Gradle version
        run: ./gradlew --version

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Generate documentation with Javadoc
        run: |
          echo '-classpath "./FtcRobotController/:' >> ./jdtclsp.txt
          carray=( $(find ~/.gradle/caches/ -name "classes.jar"  -not -type d) )
          rarray=( $(find ~/.gradle/caches/ -name "res" -type d) )
          marray=( $(find ~/.gradle/caches/ -name "AndroidManifest.xml"  -not -type d) )
          # COPY OUT ALL THE PATHS IN THIS CLASSPATH TO OUR OWN PATH - IF NEEDED
          for i in ${carray[@]}
          do
              echo $i >> ./jdtclsp.txt
              echo ":" >> ./jdtclsp.txt
          done
          for i in ${rarray[@]}
          do
              echo $i >> ./jdtclsp.txt
              echo ":" >> ./jdtclsp.txt
          done
          for i in ${marray[@]}
          do
              echo $i >> ./jdtclsp.txt
              echo ":" >> ./jdtclsp.txt
          done
          echo '$ANDROID_HOME/platforms/android-29/android.jar"' >> ./jdtclsp.txt
          STR=$( cat ./jdtclsp.txt )
          STR=${STR//$'\n'/}
          echo "String"
          echo $STR
          rm -rf ./jdtclsp.txt
          echo $STR >> ./jdtclsp.txt
          javadoc -Xdoclint:none -public -splitindex -use -author -version -d ./javadoc-output -link https://docs.oracle.com/en/java/javase/11/docs/api/ -link https://xaverianteamrobotics.github.io/FtcRobotController/javadocs/libs/ftccommon/ -link https://xaverianteamrobotics.github.io/FtcRobotController/javadocs/libs/hardware/ -link https://xaverianteamrobotics.github.io/FtcRobotController/javadocs/libs/inspection/ -link https://xaverianteamrobotics.github.io/FtcRobotController/javadocs/libs/onbotjava/ -link https://xaverianteamrobotics.github.io/FtcRobotController/javadocs/libs/robotcore/package-list @./jdtclsp.txt -tag "apiNote:a:API Note:" -tag "implSpec:a:Implementation Requirements:" -tag "implNote:a:Implementation Note:" $(find ./TeamCode/ -name "*.java" -not -type d) --ignore-source-errors

      - name: Upload the Javadoc output
        uses: actions/upload-artifact@v2
        with:
          name: Javadoc-output
          path: ./javadoc-output/

      - name: Commit and push the new Javadoc folder
        run: |
          # Set up Git and environment variables
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          shopt -s dotglob
          export BRANCH_NAME=$(echo $GITHUB_REF | sed -e "s/refs\/heads\///")
          # Move Javadoc output and build reports
          mv javadoc-output/ ..
          mkdir ../team-reports/
          mv ./TeamCode/build/reports/*  ../team-reports/
          mkdir ../sdk-reports/
          mv ./FtcRobotController/build/reports/* ../sdk-reports/
          # Checkout gh-pages branch
          git reset --hard HEAD
          git clean -f -d -x
          git remote set-branches origin --add 'gh-pages'
          git fetch -a -v
          git checkout gh-pages
          # Copy Javadoc docs to gh-pages
          rm -rf ./javadocs/${BRANCH_NAME}/ || true
          mkdir -p ./javadocs/${BRANCH_NAME}/
          mv ../javadoc-output/* ./javadocs/${BRANCH_NAME}/
          # Copy build reports to gh-pages
          rm -rf ./reports/${BRANCH_NAME}/ || true
          mkdir -p ./reports/${BRANCH_NAME}/team-reports/
          mkdir -p ./reports/${BRANCH_NAME}/sdk-reports/
          mv ../team-reports/* ./reports/${BRANCH_NAME}/team-reports/
          mv ../sdk-reports/* ./reports/${BRANCH_NAME}/sdk-reports/
          mv ./reports/${BRANCH_NAME}/team-reports/lint-results-debug.html ./reports/${BRANCH_NAME}/team-reports/index.html || true
          mv ./reports/${BRANCH_NAME}/sdk-reports/lint-results-debug.html ./reports/${BRANCH_NAME}/sdk-reports/index.html || true
          # Commit and push changes
          git add -A
          git commit -a -m "Javadoc documentation update ($GITHUB_RUN_NUMBER)
          Information:
            Repository: $GITHUB_REPOSITORY
            Branch: $GITHUB_REF
            Commit: $GITHUB_SHA
            Who triggered action: $GITHUB_ACTOR"
          git push
